### ISSUE TITLE
Update component while searching

### ISSUE THREAD

**Issue by dyseh** [socialtables/react-infinity-menu#31]
First of all, awesome component!  I'm customizing this component to show a leaf as "selected" when it is clicked.  I do this by setting an "onClick" function to the leaf which goes and updates the leaf with a customComponent.  This work just fine when the component is not in searching mode.  When it is in searching mode, my function updates the particular leaf with the customComponent but the changes are not reflected until I clear out my search.  I'm not sure how to force the component to update even when it's in searching mode. 

Thanks!

**Comment by tiansijie** [comment]
@dyseh thanks for using this component. Form what I can tell, the search should not be changing the leaf component. Do you mind sharing your leaf and the customComponent?

**Comment by dyseh** [comment]
Thank you for the reply.  I think you misunderstood me.  This is what I'm doing:

I have a tree, with nodes and leaves.  The leaves have a unselectedCustomComponent and are styled a certain way and look to be "unselected".  When someone clicks on a leaf, I go and change the leaf's custom component to a selectedCustomComponent.  This way it looks selected by the user.  This works in all cases except when the menu is in search mode.  If i search of a leaf, and click on it, the tree doesn't rerender causing the leaf to still look unselected.  However, if I get out of search mode and go find that leaf, it does have the styling of it being selected.   Does this make sense?   Is this the proper way to achieve this functionality?

Thanks again,
DyseH

**Comment by tiansijie** [comment]
Usually I use one component instead. You can put your logic for select/unselect inside one customComponent.

**Comment by dyseh** [comment]
@tiansijie  I believe that still won't solve the issue of the component not updating in 'search mode'.  Am I wrong?

**Comment by tiansijie** [comment]
@dyseh I think you are right, we are currently blocking the tree to update when in search mode. A fix will come soon. Thanks for your question, very helpful!

**Comment by dyseh** [comment]
@tiansijie Thank you for looking into it!

**Comment by conorhastings** [comment]
@dyseh please try out `v2.4.0`

**Comment by dyseh** [comment]
@conorhastings @tiansijie Thanks you, just tried it and now it works are expected.  Thank you again!
