### ISSUE TITLE
too many leaves

### ISSUE THREAD

**Issue by skoschik** [socialtables/react-infinity-menu#33]
Would love a way to set a limit for the maximum number of leaves that should be rendered initially.  With the ability to 'load more' or something, nothing fancy haha.   Not sure if something like that fits into the scope here but i thought it would be a nice add, really helps if you have a lot of child nodes. Not sure how or if i could tap into doing something like this.

...i guess i could do something with the data i feed into react-infinity-menu through props... but that seems to defeat the purpose.

Any thoughts?

**Comment by tiansijie** [comment]
this is a good idea. i am think about this recently as well.  Since the whole tree is just an array, implementation should not be really hard. If you have any idea how to implement this that would be great!

**Comment by skoschik** [comment]
I don't like the idea of looking at the parent's children while at the current node level, but it works to get the idea across.  I'm sure there's a better implementation for this but for now my use case can tolerate the extra cycles.
