### ISSUE TITLE
Is there a way to add animation?

### ISSUE THREAD

**Issue by ferpintado** [socialtables/react-infinity-menu#38]
Hi, I am currently using this component for a project I am working on and I loved it.

Is there any way to add an animation when the submenu opens, collapse animation perhaps?

Thanks in advance.

**Comment by tiansijie** [comment]
yes, since all the leafs can be customized, you provide your own customize component and add animation on it. We do have a very simple [css](https://github.com/socialtables/react-infinity-menu/blob/master/src/infinity-menu.css) that you can customized using it

**Comment by ferpintado** [comment]
Great. I will give it a try.

Thanks
