### ISSUE TITLE
in "onLeafMouseClick", an "data-reactid" of the leaf is passed in instead of the "leaf" object when using customComponent for leaf

### ISSUE THREAD

**Issue by LogicMonsters** [socialtables/react-infinity-menu#39]
Background:

    Leaf is using customized component, and in customized component, onClick = { onClick } just do exactly like the doc. (Everything is normal for Node component even if I use customComponent for nodes. )

And in InfinityMenu,  this prop is set :

 `onLeafMouseClick={this.onLeafMouseClick.bind(this)}`, 

However,
```

onLeafMouseClick(event, leaf) {
  console.log(leaf); // it is a string which is the leaf's data-reactid, not leaf object, but everything works well if I don't use customzied component
}
```

Is that a bug I guess ?

**Comment by tiansijie** [comment]
I think on the customize component, you can access the left object using `this.props.data`

**Comment by LogicMonsters** [comment]
yep, you are absoultely right. that is what I am doing right now. But still wondering if there is a way that this  issue could be fixed ?

**Comment by LogicMonsters** [comment]
And anither question is, in the customzied component for Node, is there a way that I could get access to `keyPath ` property ? (I found there is no such prop in `this.props.data` or `this.props` in node customized component)

**Comment by tiansijie** [comment]
>  But still wondering if there is a way that this issue could be fixed ?
Yes, you are right, we should probably fix this to match what we have in our doc.


>And another question is, in the customzied node component, is there a way that I could get access to keyPath property ? (I found there is no such prop in this.props.data or this.props in node customized component)

You are right, we don't put the `keypath` to the node component. Will fix that as well.

Thanks a lot for pointing that out

**Comment by LogicMonsters** [comment]
Thank you very much! Waiting for you update
