### ISSUE TITLE
Search functionality not working as expected with numeric values

### ISSUE THREAD

**Issue by juturu8989** [socialtables/react-infinity-menu#45]
When I enter a numeric value in the search box, the tree filters and shows correct results but when I erase the search input(numeric value) from search box then it's not showing the original tree instead it's still showing filtered results. Interestingly it's working as expected with alphabets.

Initially, I was using version 3.0.1 later I upgraded to version 3.2.0 but the issue still exists.

Any help greatly appreciated.

**Comment by juturu8989** [comment]
Hi, Can anyone has an idea on this?

**Comment by tiansijie** [comment]
@juturu8989 could you tell me what numeric value you input to the search box? from the test I did on the example seems working fine for me.

![in](https://user-images.githubusercontent.com/3675602/32991762-ca83b7c0-cd0f-11e7-9269-66b77490fffc.gif)

**Comment by juturu8989** [comment]
I am filtering with numeric values 0,2,4 and 6.  I don't see any errors in the console. I also found that issue is not only with numerics but also with alphabets too.
Let say my tree has
Tree
    |Apple
    |Oragne
    |Mango

Search input is 'P' - it shows only Apple. Then I erased 'P' from search input then it doesn't show the original tree with 3 elements(Apple, Orange, and Mango) but it shows still Apple only.
Interestingly if I search with 'O' then it shows Orange and Mango. And if I erase 'O' from search input then it doesn't show all 3 elements but it shows only Mango and Orange.

I tried your live demo but I couldn't find the search box on your Live Demo to verify my use case.
Please share the URL where I can filter with input.

**Comment by tiansijie** [comment]
@juturu8989 just updated the example pages http://socialtables.github.io/react-infinity-menu/
