### ISSUE TITLE
Custom component as leaf in main menu level

### ISSUE THREAD

**Issue by tomcohen** [socialtables/react-infinity-menu#46]
hi,

i am trying to set custom "onClick" function to custom component on first menu level. (He has no parent and no child)

` tree: [
        {
          name: Translation.t('sideMenu.sendRecommendation'),
          id: 0,
          isOpen: true,
          customComponent: SideMenuNode,
          onLeafMouseClick :this.onClick,
          link: 'forms/recommendation'      
        },]`

when i add to this tree object a children:[] (empty array) there is a way to pass onclick function via props?
i check the code and i think there isnt.

when i pass this tree object as leaf at main level he failed when try to search his parent.

from your code:

`/*the leaves*/
			if (!curr.children) {
				var keyPathArray = keyPath.split(".");
				var parentPath = Object.assign([], keyPathArray).splice(0, keyPathArray.length - 2);
				var parentNode = (0, _get3.default)(this.props.tree, parentPath);
				var filteredChildren = parentNode.children.some(function (child) {
					return child.isSearchDisplay === true;
				}) ? parentNode.children.filter(function (child) {
					return child.isSearchDisplay === true;
				}) : parentNode.children;
				var itemKey = "infinity-menu-leaf-" + curr.id;
				var visIds = filteredChildren.map(function (e) {
					return e.id;
				});`

failed here:

`var parentNode = (0, _get3.default)(this.props.tree, parentPath);
				var filteredChildren = parentNode.children.some(function (child)`

there is any option to do it?

**Comment by tiansijie** [comment]
you could not set any children and pass onNodeClick as the props for onClick function on the tree node.
